.\" (c) 2005-2007 Tom Beaumont <tombeaumont@yahoo.com>
.\" (c) 2007 Miriam Ruiz <little_miry@yahoo.es>
.\" (c) 2007 Helge Kreutzmann <debian@helgefjell.de>
.\"
.\" This document is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this package; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.TH "Hex\(hya\(hyhop" "6" "" "" ""
.SH "NAME"
hex\-a\-hop \- puzzle game based on hexagonal tiles
.SH "DESCRIPTION"
Hex\(hya\(hyhop is a puzzle game based on hexagonal tiles. There is no time limit and no real\(hytime element.

The objective is simply to destroy all the green hexagonal tiles on each of the 100 levels. As you progress through the game, more types of tiles are introduced which make things more difficult and interesting.

.SH "USAGE"
You can move the character around with the keys Q,W,E,A,S,D, or with the numeric keypad. Alternatively, you can use the mouse and click on the tile you'd like to move to.

Use 'U', backspace or the right mouse button to undo mistakes.
The 'Esc' key (or middle mouse button) brings up a menu from which you can restart if you get stuck.

Your goal is to break all the green tiles. You mainly do this by jumping on them. They will crack when you land on them, and only disintegrate when you jump off. Try not to trap yourself!

During the game, you will be given hints and instructions on what to do. Use the cursor keys or click on the arrows to scroll through the help pages. More pages will be added as you progress through the game, as new tiles will keep appearing.

You can choose which level to attempt next from the map screen. Silver levels are ones you've cleared. Black levels are ones you haven't completed yet, but are available to play.

There is no time limit and no real\(hytime element, so take as long as you like.
.SH "SEE ALSO"
You can find more about the game on its homepage: https://hexahop.sourceforge.net/

In Debian's version, game data is stored in the directory $HOME/.hex\-a\-hop/. If the environment variable $HOME is not set, it'll use /tmp/ instead.

.SH "AUTHOR"
The game has been written by Tom Beaumont, and is distributed under the GNU General Public License, either version 2 of the License, or (at your option) any later version.

